site_name: CoMA
theme:
  name: material
  palette:
    scheme: indigo

markdown_extensions:
  - codehilite:
      use_pygments: true
      css_class: highlight
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Getting Started:
    - Overview: getting-started/getting-started
    - Installation: getting-started/installation
    - Creating a New Project: getting-started/creating-a-new-project
    - Creating Modules: getting-started/creating-modules
    - Running the Agent: getting-started/running-the-agent
  - API Reference: api.md